version: "3.8"
services:
  user_profile_db: 
    image: postgres:latest
    container_name: user_profile_postgres 
    restart: always
    env_file:
      - ./.env.dev


  user_profile_service: 
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    depends_on:
      - user_profile_db 
    volumes:
    - ./coverage_reports:/work/coverage_reports
    