version: "3.8"

networks:
  apigateway_system_network:
    external: true

services:
  user_profile_service: 
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - ./.env.prod
    hostname:
      user_profile_service 
    networks:
      - apigateway_system_network
  
  user_profile_db:
    env_file:
      - ./.env.prod
    hostname:
      user_profile_db 
    networks:
      - apigateway_system_network